services:
  - type: web
    name: transpose-service
    env: python
    buildCommand: pip install -r transpose_x/backend/requirements.txt
    startCommand: gunicorn transpose:app
    workingDir: transpose_x/backend