services:
  - type: web
    name: transpose-service
    env: python
    buildCommand: cd transpose_x/backend && pip install -r requirements.txt
    startCommand: cd transpose_x/backend && gunicorn transpose:app
    buildFilter:
      paths:
        - transpose_x/backend/**